server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  application:
    name: dojo-members
  datasource:
    url: jdbc:postgresql://localhost:5432/dojo_member
    username: "{cypher}29811496885823548d49fb7d94f510f63116eacf498b343e480e4339adb2de08"
    password: "{cypher}29811496885823548d49fb7d94f510f63116eacf498b343e480e4339adb2de08"
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: none
  data:
    rest:
      detection-strategy: ANNOTATED # Disable automatic repository REST exposure
  flyway:
    enabled: true
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
