server:
  port: 8181

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  application:
    name: martial-art-service
  datasource:
    url: jdbc:postgresql://martial-art-db:5433/dojo_martial_art
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: none
  data:
    rest:
      detection-strategy: ANNOTATED # Disable automatic repository REST exposure
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: Martial Art Management
    description: Service for managing martial arts in the dojo
    version: 1.0.0
