server:
  port: 8080

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

spring:
  application:
    name: member-service
  datasource:
    url: '{cipher}491aa212f2604ca2aa3e44bd87cbd1c57cae8d8d233d6063ac11965c01e74237ae98d2ffc945ec4435f8770dc589b5c9{cipher}743a854ca0e0684b48cbe04c66c9088762630174a015bb916eb5d826f6d868ebea84fc4fbaefe0e7ce76e44556faf3b8'
    username: '{cipher}b79738f3081388c91113e4f74a64c996a86fce482ea1f7ca5a841a2bd5a9bfb5'
    password: '{cipher}b79738f3081388c91113e4f74a64c996a86fce482ea1f7ca5a841a2bd5a9bfb5'
  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        show_sql: true
    hibernate:
      ddl-auto: none
  data:
    rest:
      detection-strategy: ANNOTATED # Disable automatic repository REST exposure
  flyway:
    enabled: true
    locations: classpath:db/migration
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
